= Pre-requisites
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:idprefix:
:idseparator: -
:sectlinks:
:toc:
:toc-placement!:

:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-vcn
:uri-rel-file-base: link:{uri-repo}/blob/main
:uri-rel-tree-base: link:{uri-repo}/tree/main
:uri-docs: {uri-rel-file-base}/docs

:uri-oci: https://cloud.oracle.com/cloud-infrastructure
:uri-oci-compartment: https://docs.cloud.oracle.com/iaas/Content/Identity/Tasks/managingcompartments.htm#two
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-oci-documentation: https://docs.cloud.oracle.com/iaas/Content/home.htm
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#two
:uri-terraform: https://www.terraform.io
:uri-terraform-download: https://www.terraform.io/downloads.html
:uri-hashicorp-brew-tap-announcement: https://www.hashicorp.com/blog/announcing-hashicorp-homebrew-tap
:uri-homebrew: https://brew.sh/
:uri-chocolatey: https://chocolatey.org/

This section will guide you through the pre-requisites before you can use this project.

You can proceed to the xref:quickstart.adoc[Quick Start guide] if you have already done these steps.

toc::[]

== Install Terraform

Start by installing Terraform wth the proper package for your operating system and architecture.

=== Installing Terraform on Oracle Linux

On Oracle Linux, you can install Terraform using from your distribution's package repository.

For Oracle Linux 7:

[source,bash]
----
yum -y install oraclelinux-developer-release-el7 && yum -y install terraform
----

For Oracle Linux 8:

[source,bash]
----
dnf -y install oraclelinux-developer-release-el8 && dnf -y install terraform
----

=== Installing Terraform on macOS

On macOS, you can install Terraform using {uri-homebrew}[Homebrew].

[source,bash]
----
brew install hashicorp/tap/terraform
----

This will install Terraform using the official HashiCorp Homebrew tap. For more details about the differences and benefits to use the community maintained or the official Homebrew tap, see {uri-hashicorp-brew-tap-announcement}[HashiCorp's announcement]

NOTE: If Homebrew is not already installed on your system, start by installing it following the installation instructions at https://brew.sh

=== Installing Terraform on Windows

On Windows, you can install Terraform using {uri-chocolatey}[Chocolatey].

[source,powershell]
----
choco install terraform
----

NOTE: If Chocolatey is not already installed on your system, start by installing it following the installation instructions on https://chocolatey.org/

=== Manual installation

For manual installation, follow the instructions on {uri-terraform-download}[Terraform download page].

== Generate and upload your OCI API keys

Follow the documentation for {uri-oci-keys}[generating and uploading your API keys].

Note the key fingerprint.

== Create an OCI compartment

Follow the documentation for {uri-oci-compartment}[creating a compartment].

== Obtain the necessary OCIDs

The following OCIDs are required:

. Compartment OCID
. Tenancy OCID
. User OCID

Follow the documentation for {uri-oci-ocids}[obtaining the tenancy and user ocids].

To obtain the compartment OCID:

1. Navigate to Identity > Compartments
2. Click on your Compartment
3. Locate OCID on the page and click on `Copy`
