= Quickstart
:idprefix:
:idseparator: -
:sectlinks:
:toc:

:uri-repo: https://github.com/oracle-terraform-modules/terraform-oci-vcn
:uri-rel-file-base: link:{uri-repo}/blob/main
:uri-rel-tree-base: link:{uri-repo}/tree/main
:uri-docs: {uri-rel-file-base}/docs
:uri-oci-keys: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm
:uri-oci-ocids: https://docs.cloud.oracle.com/iaas/Content/API/Concepts/apisigningkey.htm#five
:uri-terraform: https://www.terraform.io
:uri-terraform-oci: https://www.terraform.io/docs/providers/oci/index.html
:uri-terraform-options: {uri-docs}/terraformoptions.adoc
:uri-variables: {uri-rel-file-base}/variables.tf


== Assumptions

1. You have setup the {uri-oci-keys}[required keys]
2. You know the {uri-oci-ocids}[required OCIDs]
3. You have the necessary permissions

== Pre-requisites

1. Git is installed
2. SSH client is installed
3. Terraform 1.0.0 or greater is installed

== Instructions

=== Provisioning using this git repo

. Clone the repo:

+
[source,bash]
----
git clone https://github.com/oracle-terraform-modules/terraform-oci-vcn.git tfvcn

cd tfvcn

cp terraform.tfvars.example terraform.tfvars
----

. Create a provider.tf file and add the following:

+
[source,hcl]
----
provider "oci" {
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
}

# provider identity parameters
variable "api_fingerprint" {
  description = "fingerprint of oci api private key"
  type        = string
}

variable "api_private_key_path" {
  description = "path to oci api private key used"
  type        = string
}

variable "tenancy_id" {
  description = "tenancy id where to create the sources"
  type        = string
}

variable "user_id" {
  description = "id of user that terraform will use to create the resources"
  type        = string
}
----

. Set mandatory provider parameters in terraform.tfvars:

* `api_fingerprint`
* `api_private_key_path`
* `region`
* `tenancy_id`
* `user_id`

. Override other parameters in terraform.tfvars:

* `compartment_id`
* `label_prefix`
* `vcn_dns_label`
* `vcn_name`

. Optional parameters to override:

* `create_internet_gateway`
* `create_nat_gateway`
* `create_service_gateway`
* `freeform_tags`
* `attached_drg_id`

. Run Terraform:

+
[source,bash]
----
terraform init
terraform plan
terraform apply
----

=== Provisioning using the HashiCorp registry module

You can also use the method below to reuse this in your own module.

. Create a variable.tf file in your root project and add the following:
+
[source, hcl]
----
include::../examples/module_composition/variables.tf[lines=3..-1]
----

. Create a provider.tf file in your root directory and add the following:
+
[source,hcl]
----
provider "oci" {
  fingerprint          = var.api_fingerprint
  private_key_path     = var.api_private_key_path
  region               = var.region
  tenancy_ocid         = var.tenancy_id
  user_ocid            = var.user_id
}
----

. Create a main.tf file and add the following:
+
[source,hcl]
----
include::../examples/module_composition/main.tf[lines=3..-1]
----

. Copy terraform.tfvars.example to terraform.tfvars and set the mandatory provider parameters:
+
[source,bash]
----
cp terraform.tfvars.example terraform.tfvars
----

* `api_fingerprint`
* `api_private_key_path`
* `region`
* `tenancy_id`
* `user_id`

. Override other parameters in terraform.tfvars:

* `compartment_id`
* `label_prefix`
* `vcn_dns_label`
* `vcn_name`

. Optional parameters to override:

* `attached_drg_id`
* `create_internet_gateway`
* `create_nat_gateway`
* `create_service_gateway`
* `freeform_tags`
* `defined_tags`

. Run Terraform:
+
[source,bash]
----
terraform init
terraform plan
terraform apply
----

== Related documentation:

* {uri-terraform-options}[All Terraform configuration options] for {uri-repo}[this project]
